from __future__ import annotations

from fractions import Fraction
import itertools

from vortex_runtime.causal_bilinear_query_restriction import (
    EVALUATION_QUERY_COUNT,
    HOT_STATE_BYTES,
    P50_TARGET_FRACTION,
    REGISTERED_RANK_PRIMES,
    aligned_pair_coordinate_count,
    derive_frontier,
    factor_scan_address_counts,
    fingerprint_union_bound,
    largest_scannable_span_dimension,
    ledger_state_bytes,
    maximum_weighted_fallback_misses,
    minimum_rejecting_rank,
    one_down_projection_coefficients,
    operation_fraction_before_fallback,
    span_miss_lower_bound,
    traffic_fraction_before_fallback,
)
from vortex_runtime.query_adaptive_cold_equation import (
    REGISTERED_NON_EMBEDDING_COEFFICIENTS,
)


def _gf2_rank(words: list[int] | tuple[int, ...]) -> int:
    pivots: dict[int, int] = {}
    for word in words:
        current = word
        while current:
            pivot = current.bit_length() - 1
            if pivot not in pivots:
                pivots[pivot] = current
                break
            current ^= pivots[pivot]
    return len(pivots)


def _span(basis: tuple[int, ...]) -> set[int]:
    values = {0}
    for row in basis:
        values |= {value ^ row for value in tuple(values)}
    return values


def _outer_word(left: int, right: int, rows: int, columns: int) -> int:
    word = 0
    for row in range(rows):
        for column in range(columns):
            if ((left >> row) & 1) and ((right >> column) & 1):
                word |= 1 << (row * columns + column)
    return word


def test_registered_pair_population_and_dimension_are_frozen() -> None:
    assert aligned_pair_coordinate_count() == 39_109_888
    assert one_down_projection_coefficients() == 872_415_232
    assert EVALUATION_QUERY_COUNT == 36
    assert REGISTERED_RANK_PRIMES == (65_521, 65_519, 65_497)


def test_shape_only_scan_boundary_is_exactly_twenty_three() -> None:
    dimension = largest_scannable_span_dimension()
    assert dimension == 23
    assert traffic_fraction_before_fallback(dimension) < P50_TARGET_FRACTION
    assert operation_fraction_before_fallback(dimension) < P50_TARGET_FRACTION
    assert ledger_state_bytes(dimension) < HOT_STATE_BYTES
    assert traffic_fraction_before_fallback(dimension + 1) > P50_TARGET_FRACTION


def test_rank_forces_misses_for_every_best_posthoc_subspace() -> None:
    # Exhaust all subspaces generated by up to two vectors in F_2^4 and all
    # populations of four distinct vectors.  The number of population vectors
    # outside any B-dimensional subspace is always at least rank-B.
    ambient = tuple(range(1 << 4))
    for first, second in itertools.product(ambient, repeat=2):
        subspace = _span((first, second))
        dimension = _gf2_rank((first, second))
        for population in itertools.combinations(ambient, 4):
            rank = _gf2_rank(population)
            misses = sum(word not in subspace for word in population)
            assert misses >= span_miss_lower_bound(rank, 4, dimension)


def test_outer_product_population_can_reach_full_observed_rank() -> None:
    tensors = [
        _outer_word(0b01, 0b01, 2, 2),
        _outer_word(0b01, 0b10, 2, 2),
        _outer_word(0b10, 0b01, 2, 2),
        _outer_word(0b10, 0b10, 2, 2),
    ]
    assert _gf2_rank(tensors) == 4
    assert span_miss_lower_bound(4, 4, 2) == 2


def test_dependent_outer_products_receive_no_false_rank_credit() -> None:
    first = _outer_word(0b11, 0b01, 2, 2)
    duplicate = _outer_word(0b11, 0b01, 2, 2)
    zero = _outer_word(0b00, 0b11, 2, 2)
    assert _gf2_rank([first, duplicate, zero]) == 1
    assert span_miss_lower_bound(1, 3, 1) == 0


def test_last_down_weighted_fallback_threshold_is_four_rows() -> None:
    dimension = largest_scannable_span_dimension()
    common = traffic_fraction_before_fallback(dimension)
    allowed = maximum_weighted_fallback_misses(
        population_size=EVALUATION_QUERY_COUNT,
        matrix_coefficients=one_down_projection_coefficients(),
        common_fraction=common,
    )
    assert allowed == 4
    assert minimum_rejecting_rank(
        population_size=EVALUATION_QUERY_COUNT,
        span_dimension=dimension,
        allowed_misses=allowed,
    ) == 28


def test_independent_heldout_counterexample_exceeds_the_complete_target() -> None:
    result = derive_frontier()
    counterexample = result["strongest_counterexample"]
    assert counterexample["all_evaluation_tensors_independent_rank"] == 36
    assert counterexample["oracle_miss_rows"] == 13
    assert counterexample["target_miss_factor"] > 1.04


def test_factor_scan_address_rounding_is_reported_not_called_hardware() -> None:
    counts = factor_scan_address_counts(23)
    assert counts == {
        "vector_segments": 40_618,
        "rounded_64_byte_lines": 28_110_232,
        "rounded_4k_pages": 442_129,
    }
    result = derive_frontier()
    assert result["claim_boundary"]["model_or_hardware_execution"] == "NOT RUN"


def test_fingerprint_error_is_union_accounted_but_not_exact_membership() -> None:
    bound = fingerprint_union_bound()
    assert bound > 0
    assert float(bound) < 1.5e-17
    result = derive_frontier()
    contract = result["fingerprint_contract"]
    assert contract["exact_rational_witness_required_before_hit"] is True
    assert contract["modular_nonincrease_alone_is_not_a_hit"] is True


def test_result_preserves_pair_extractor_and_core_claim_boundary() -> None:
    result = derive_frontier()
    assert result["decision"] == (
        "PREREGISTER_LAST_DOWN_CAUSAL_BILINEAR_RANK_GATE_ONLY"
    )
    assert "FREE FAVORABLE ORACLE" in result["resource_equation"][
        "pair_extraction"
    ]
    assert result["claim_boundary"]["core_candidate"].startswith("NONE")
    assert Fraction(
        result["rank_gate"]["registered_down_fraction"]
    ) == Fraction(
        one_down_projection_coefficients(),
        REGISTERED_NON_EMBEDDING_COEFFICIENTS,
    )
